mainapp/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

from django.contrib.auth.decorators import login_required

urlpatterns = [
	path('', LoginView.as_view(), name = "login"),
	path('logout/', Logout.as_view(), name = "logout"),

	# URL related to customer process
	path('customers/', (CustomerView.as_view()), name = "customers"),
	path('search-address/', (SearchCustomer.as_view()), name = "search_address"),
	path('edit-customer/', (EditCustomer.as_view()), name = "edit_customer"),

	# URL related to job process
	path('jobs/', (Jobs.as_view()), name = "jobs"),
	path('search-jobs/', (SearchJobs.as_view()), name = "search_jobs"),
	path('edit-job/', (EditJobLocation.as_view()), name = "edit_job"),

	# URL related to order process
	path('order/', (OrderView.as_view()), name = "order"),

	path('order-search/', (OrderSearch.as_view()), name='order-search'),
	path('order-list/', (OrderListing.as_view()), name='order-list'),
	path('order-delete/', (OrderDelete.as_view()), name='order-delete'),
	path('edit-order/<int:order_id>', (EditOrder.as_view()), name='edit-order'),
	
]

vendor_application/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("mainapp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Customerinformation(models.Model):
	""" This table for store Customer details. """
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	company = models.CharField(max_length=200)
	biling_address = models.CharField(max_length=200)
	city = models.CharField(max_length=200)
	state = models.CharField(max_length=200)
	postal_code = models.CharField(max_length=200)
	home_phone = models.CharField(max_length=200, null = True, blank = True)
	business_phone = models.CharField(max_length=200)
	fax_number = models.CharField(max_length=200, null = True, blank = True)
	cell_phone = models.CharField(max_length=200, null = True, blank = True)
	created_at  = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.user.first_name

class JobLocation(models.Model):
	""" This table for store Job Location. """
	customer = models.OneToOneField(Customerinformation, on_delete=models.CASCADE)
	first_name = models.CharField(max_length=200)
	last_name = models.CharField(max_length=200, null = True, blank = True)
	phone_number = models.CharField(max_length=200, null = True, blank = True)
	address = models.TextField(max_length=500, null = True, blank = True)
	state = models.CharField(max_length=200)
	city = models.CharField(max_length=200, null = True, blank = True)
	postal_code = models.CharField(max_length=200, null = True, blank = True)
	

	# def __str__(self):
	# 	return self.customer


class Order(models.Model):
	""" This table for store Order. """
	customer = models.ForeignKey(Customerinformation, on_delete=models.CASCADE)
	order_id = models.CharField(max_length=50,null = True, blank = True)
	labor = models.CharField(max_length=200,null = True, blank = True)
	labor_price = models.FloatField(default = 0.0)
	floor_prep = models.CharField(max_length=200, null = True, blank = True)
	floor_prep_price = models.FloatField(default = 0.0)
	sub_floor = models.CharField(max_length=200, null = True, blank = True)
	sub_floor_price = models.FloatField(default = 0.0)
	appliances = models.CharField(max_length=200, null = True, blank = True)
	appliances_price = models.FloatField(default = 0.0)
	miscellaneous = models.CharField(max_length=200, null = True, blank = True)
	miscellaneous_price = models.FloatField(default = 0.0)
	price_includes = models.CharField(max_length=200, null = True, blank = True)
	price_includes_price = models.FloatField(default = 0.0)
	trim = models.CharField(max_length=200, null = True, blank = True)
	trim_price = models.FloatField(default = 0.0)
	sub_total = models.FloatField(default = 0.0)
	sales_tax = models.CharField(max_length=200,null = True, blank = True)
	total = models.FloatField(default = 0.0)
	deposit = models.FloatField(default = 0.0)
	balance_due = models.FloatField(default = 0.0)
	is_deleted = models.BooleanField(default = False)
	invoice_file = models.FileField(upload_to='invoices/',blank=True)
	created_at  = models.DateTimeField(auto_now_add=True, null =True,blank=True)
	updated_at = models.DateTimeField(auto_now=True, null =True,blank=True)

	# def __str__(self):
	# 	return self.customer

class Products(models.Model):
	""" This table for store Products. """
	order = models.ForeignKey(Order, on_delete=models.CASCADE, null = True)
	product_name = models.CharField(max_length=200)
	color = models.CharField(max_length=200, null = True, blank = True)
	qty = models.CharField(max_length=200, null = True, blank = True)
	area = models.CharField(max_length=500, null = True, blank = True)
	price = models.FloatField()
	

	# def __str__(self):
	# 	return self.customer

class Notes(models.Model):
	""" This table for store Customer Notes. """
	order = models.ForeignKey(Order, on_delete=models.CASCADE, null = True)
	customer_notes = models.TextField(max_length=500, null = True, blank = True)
	job_site_notes = models.TextField(max_length=500, null = True, blank = True)


class Terms(models.Model):
	""" This table for store order terms. """
	order = models.ForeignKey(Order, on_delete=models.CASCADE, null = True)
	terms = models.TextField(max_length=500, null = True, blank = True)

templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
    <head>
        <!--=============== basic  ===============-->
        <meta charset="UTF-8">
        <title>Jack Hyman</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta name="robots" content="index, follow"/>
        <meta name="keywords" content=""/>
        <meta name="description" content=""/>
        <!--=============== css  ===============-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link type="text/css" rel="stylesheet" href="{% static 'css/reset.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/plugins.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/color.css' %}">        <!--=============== favicons ===============-->
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
        {% block css %}

        {% endblock %}
    </head>
    
  	<body class="fixed-sn light-blue-skin">

<div class="top-nav">
	<nav class="navbar navbar-expand">
                <div class="container-fluid">
                	<div class="d-flex juustify-content-between w-100">
	                	<!-- <button type="button" id="sidebarCollapse" class="hamburger animated fadeInLeft is-closed toggle-icon">
	                         <span class="hamb-top"></span>
	                     <span class="hamb-middle"></span>
	                     <span class="hamb-bottom"></span>
	                    </button> -->

	                   <!-- <a class="logo navbar-brand" href="/">
	                    <img class="logo_img_1" src="/static/website/images/logo2.png" alt="logo">
	                   </a> -->

	                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
	                        <ul class="nav navbar-nav ml-auto">
	                           
	                           <li class="nav-item dropdown">
						        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						          Orders
						        </a>
						        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
						          <a class="dropdown-item" href="{% url 'customers' %}">Create New Order</a>
						          <a class="dropdown-item" href="{% url 'order-list' %}">Modify Existing Order</a>
						          <a class="dropdown-item" href="{% url 'order-search' %}">Lookup Order</a>
                      <form id="logoutform" method="POST" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <input type="hidden">
                          <a class="dropdown-item" href="javascript: void(0)" id="logout_btn">Logout</a>
                      </form>
						          <!-- <div class="dropdown-divider"></div> -->
						          
						        </div>
						      </li>
	                             <li class="nav-item for-desktop">
	                               <a class="nav-link" href="/leaderboard">Reports</a>
	                            </li>
	                             <li class="nav-item for-desktop">
	                               <a class="nav-link" href="/refer">Admin</a>
	                            </li>
	                        </ul>
	                    </div>
	                </div>
                     
                </div>
            </nav>
</div>



 {% block content %}
      {% endblock %}

<!-- Main end -->
<!--=============== scripts  ===============-->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="{% static 'js/jquery.min.js' %}"></script>      
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
</body>
    <script>
     $('#sidebarCollapse').on('click', function () {
      $('#sidebar').addClass('active');
      $('.overlay').addClass('active');
      $('.collapse.in').toggleClass('in');
      $('a[aria-expanded=true]').attr('aria-expanded', 'false');
  	});
     $('#dismiss, .overlay').on('click', function () {
      $('#sidebar').removeClass('active');
      $('.overlay').removeClass('active');
  	});

     $('#logout_btn').on('click', function () {
      $('#logoutform').submit();
     })
	 
    </script>
{% block extrascript %}
{% endblock %}

</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
    <head>
        <!--=============== basic  ===============-->
        <meta charset="UTF-8">
        <title>Jack</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta name="robots" content="index, follow"/>
        <meta name="keywords" content=""/>
        <meta name="description" content=""/>
        <!--=============== css  ===============-->
        <link type="text/css" rel="stylesheet" href="{% static 'css/reset.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/plugins.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/color.css' %}">
        <!--=============== favicons ===============-->
        <link rel="shortcut icon" href="images/favicon.ico">
    </head>
    
  <body class="fixed-sn deep-purple-skin">
    <div id="wrapper">
     
             <!-- Form section start  -->
             <section class="signup-pg all-page-mg">
                <div class="container">
                  <div class="row">
                    <div class="col-lg-10 col-xl-9 mx-auto">
                      <div class="card card-signin flex-row my-5">
                        <div class="card-img-left d-none d-md-flex">
                           <!-- Background image for card set in CSS! -->
                        </div>
                        <div class="card-body">
                          <div class="alert-danger alert" style="text-align: center; display: none;"></div>
                        	{% if messages %}
								{% for message in messages %}
								<div class="alert text-center {% if message.tags == 'error' %}alert-danger{% else %} alert-{{ message.tags }}{% endif %}" role="alert">{{ message|safe }}</div>
								{% endfor %}
								{% endif %}
                          <h5 class="card-title text-center">Sign In</h5>
                          <form class="form-signin" action="{% url 'login' %}" method="post">
                          	{% csrf_token %}
                            <div class="form-label-group">
                             

                            <div class="form-label-group">
                              <input type="email" id="inputEmail" name="email" class="form-control" placeholder="Email address" required>
                              <label for="inputEmail">Email address</label>
                            </div>
                            
                    

                            <div class="form-label-group">
                              <input type="password" id="inputPassword" class="form-control" placeholder="Password" name="password" required>
                              <label for="inputPassword">Password</label>
                            </div>
                            
                            

                            <button class="btn btn-lg btn-primary btn-block login-btn text-uppercase" type="submit">Sign In</button>
                            <a class="d-block text-center mt-2 small" href="#">Forget Passward?</a>
                        
                          </form>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
             </section>
             <!-- /#page-content-wrapper -->
     
         </div>
         <!-- /#wrapper -->
    <!--/.Footer-->
            
        <!-- Main end -->
        <!--=============== scripts  ===============-->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="{% static 'js/jquery.min.js' %}"></script>      
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
    <script>
        $(document).ready(function () {
  var trigger = $('.hamburger'),
      overlay = $('.overlay'),
     isClosed = false;

    trigger.click(function () {
      hamburger_cross();      
    });

    function hamburger_cross() {

      if (isClosed == true) {          
        overlay.hide();
        trigger.removeClass('is-open');
        trigger.addClass('is-closed');
        isClosed = false;
      } else {   
        overlay.show();
        trigger.removeClass('is-closed');
        trigger.addClass('is-open');
        isClosed = true;
      }
  }
  
  $('[data-toggle="offcanvas"]').click(function () {
        $('#wrapper').toggleClass('toggled');
  });  
});

    $('.login-btn').click(function(){
        $('.alert-danger').hide();
        $('.alert-danger').html('');
        var email = ($("#inputEmail").val()).trim();
        var password = ($("#inputPassword").val()).trim();
        var email_pattern = /^\b[A-Z0-9._%-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b$/i
        var  submit = true;

         if (email==''|| email == null){
            $('#inputEmail').css('border', '1px solid red');
              submit = false;
        }
         else{
          $('#inputEmail').css('border', '1px solid #ced4da');         
        }
        if (password==''|| password == null){
            $('#inputPassword').css('border', '1px solid red');
             submit = false;
        }
        else{
          $('#inputPassword').css('border', '1px solid #ced4da');
        }

        if (email != "" || email == null){
      
          if(!email_pattern.test(email)){
             $('.alert-danger').append('Please enter a valid email address');
             $('.alert-danger').show();
          }
        }
        return submit;
  });
    </script>
</html>

templates/order-invoice-pdf.html
<!DOCTYPE HTML>
<html lang="en">
    <head>
        <!--=============== basic  ===============-->
        <meta charset="UTF-8">
        <title>Jack Hyman</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta name="robots" content="index, follow"/>
        <meta name="keywords" content=""/>
        <meta name="description" content=""/>
        <!--=============== css  ===============-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link type="text/css" rel="stylesheet" href="css/reset.css">
        <link type="text/css" rel="stylesheet" href="css/plugins.css">
        <link type="text/css" rel="stylesheet" href="css/bootstrap.css">
        <link type="text/css" rel="stylesheet" href="css/pdf-css.css">
        <link type="text/css" rel="stylesheet" href="css/color.css">
        <!--=============== favicons ===============-->
        <link rel="shortcut icon" href="images/favicon.ico">
    </head>

    
  	<body class="pdf-body">
  		<div class="text-right"><a href=""> Print</a></div>
  		<div class="pdf-area py-3">
  			<div class="head d-flex justify-content-between">
  				<div class="d-flex">
  					<div class="">
	  					<h6>110% INC</h6>
	  					<h6>DBA</h6>
  					</div>
  					<div class="">
  						<p>COMPANY X</p>
  					</div>

  				</div>
  				<div class="company-inc">
  					<h6>COMPANY X INC</h6>
  					<h6>555,5555.1212</h6>
  					<p>www.website.com</p>
  				</div>
  				<div class="order-dt">
  					<table class="table">
					  <tbody>
					    <tr>
					      <th scope="row">Order No.</th>
					      <td>{{add_order.order_id}}</td>
					    </tr>
					    <tr>
					      <th scope="row">Date</th>
					      <td>{{add_order.created_at|date:"Y-m-d"}}</td>
					    </tr>
					    <tr>
					      <th scope="row">Referred By:</th>
					      <td></td>
					    </tr>
					  </tbody>
					</table>
  				</div>
  			</div>	

  			<!-- second head -->
  			<div class="order-dt">
  					<table class="table">
					  <tbody>
					    <tr>
					      <th scope="row">Customer:</th>
					      <td colspan="2">{{add_order.customer.user.first_name}}</td>
					      <th scope="row">Address:</th>
					      <td colspan="2">{{add_order.customer.biling_address}}</td>
					    </tr>
					    <tr>
					      <th scope="row">City:</th>
					      <td>{{add_order.customer.city}}</td>
					      <th scope="row">Country:</th>
					      <td>{{add_order.customer.country}}</td>
					      <th scope="row">State:</th>
					      <td>{{add_order.customer.state}}</td>
					      <th scope="row">Zip:</th>
					      <td>{{add_order.customer.postal_code}}</td>
					    </tr>
					    <tr>
					      <th scope="row">Phone:</th>
					      <td colspan="2">{{add_order.customer.business_phone}}</td>
					      <th scope="row">P/C:</th>
					      <td>{{add_order.customer.cell_phone}}</td>
					      <th scope="row">Fax:</th>
					      <td>{{add_order.customer.fax_number}}</td>
					    </tr>
					  </tbody>
					</table>
  				</div>
  				<div class="form-group">
                  <input type="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Job Location" class="form-control">
                </div>
                <div class="compny-check d-flex justify-content-center">
                	<h6 class="mr-4">COMPANY X</h6>
                	<span class="form-check mr-4">
					    <input type="checkbox" class="form-check-input" id="exampleCheck1">
					    <label class="form-check-label" for="exampleCheck1">Will furnish</label>
					 </span>
					 <span class="form-check mr-4">
					    <input type="checkbox" class="form-check-input" id="exampleCheck2">
					    <label class="form-check-label" for="exampleCheck2">Will install</label>
					 </span>
                	<span>the following</span>
                </div>
                <div class="main-table">
                	<table class="table table-bordered">
					  <thead>
					    <tr>
					      <th scope="col">Product/Service #</th>
					      <th scope="col">Color/Pattern</th>
					      <th scope="col">Qty/UM</th>
					      <th scope="col">Areas</th>
					      <th scope="col">Price</th>
					    </tr>
					  </thead>
					  <tbody>
					  	{% for pro in add_order.products_set.all %}
					    <tr>
					      <td><p>{{pro.product_name}}</p></td>
					      <td><p>{{pro.color}}</p></td>
					      <td><p>{{pro.qty}}</p></td>
					      <td><p>{{pro.area}}</p></td>
					      <td><p>$ {{pro.price}}</p></td>
					    </tr>
					    {% endfor %}
					    <!-- <tr>
					      <td><p></p></td>
					      <td></td>
					      <td></td>
					      <td></td>
					      <td></td>
					    </tr>
					    <tr>
					      <td><p></p></td>
					      <td></td>
					      <td></td>
					      <td></td>
					      <td></td>
					    </tr>
					    <tr>
					      <td><p></p></td>
					      <td></td>
					      <td></td>
					      <td></td>
					      <td></td>
					    </tr>
					    <tr>
					      <td><p></p></td>
					      <td></td>
					      <td></td>
					      <td></td>
					      <td></td>
					    </tr>
					    <tr>
					      <td><p></p></td>
					      <td></td>
					      <td></td>
					      <td></td>
					      <td></td>
					    </tr> -->
					    <tr>
					      <th colspan="4">Labor</th>
					      <td>$ {{add_order.labor_price}}</td>
					    </tr>
					    <tr>
					      <th colspan="4">Floor Prep</th>
					      <td>$ {{add_order.floor_prep_price}}</td>
					    </tr>
					    <tr>
					      <th colspan="4">Sub-Floor</th>
					      <td>$ {{add_order.sub_floor_price}}</td>
					    </tr>
					    <tr>
					      <th colspan="4">Appliances</th>
					      <td>$ {{add_order.appliances_price}}</td>
					    </tr>
					    <tr>
					      <th colspan="4">Trim</th>
					      <td>$ {{add_order.trim_price}}</td>
					    </tr>
					    <tr>
					      <th colspan="4">Miscellaneous</th>
					      <td>$ {{add_order.miscellaneous_price}}</td>
					    </tr>
					   
					    <tr>
					      <th colspan="3">Price Includes</th>
					      <th class="text-right">Sub-Total</th>
					      <td>$ {{add_order.sub_total}}</td>
					    </tr>
					    <tr>
					      <th colspan="4" class="text-right">Sales Tax</th>
					      <td>{{add_order.sales_tax}} %</td>
					    </tr>
					    <tr>
					      <th colspan="4" class="text-right">Total</th>
					      <td>$ {{add_order.total}}</td>
					    </tr>
					    <tr>
					      <th colspan="4" class="text-right">50% Deposit</th>
					      <td>$ {{add_order.deposit}}</td>
					    </tr>
					    <tr>
					      <th colspan="4" class="text-right">Balance Due</th>
					      <td>$ {{add_order.balance_due}}</td>
					    </tr>

					  </tbody>
					</table>
                </div>
                <div class="row">
                	<div class="col-md-5">
		                <div class="office-use">
		                	<h5>For Office Use Only:</h5>
		                	<p>Install date: <span class="office-text"><input type="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="" class="form-control"></span></p>
		                	<p>Mfg reference: <span class="office-text"><input type="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="" class="form-control"></span></p>
		                	<p>Product receipt date: <span class="office-text"><input type="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="" class="form-control"></span></p>
		                	<p>MPS: <span class="office-text"><input type="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="" class="form-control"></span></p>
		                	<p>IPS: <span class="office-text"><input type="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="" class="form-control"></span></p>
		                	<p>MP: <span class="office-text"><input type="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="" class="form-control"></span></p>
		                	<p>IC: <span class="office-text"><input type="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="" class="form-control"></span></p>
		                	<p>MC: <span class="office-text"><input type="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="" class="form-control"></span></p>
		                	<p>GP: <span class="office-text"><input type="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="" class="form-control"></span></p>
		                </div>
		            </div>
		            <div class="col-md-5">
		            	<div class="addintinl-info form-group">
		            		<textarea class="form-control" id="exampleFormControlTextarea1" rows="15" placeholder="Additions and/or deletions to contract:"></textarea>
						</div>
		            </div>
            	</div>
            	<div class="d-flex mt-3">
	            	<div class="form-check mr-4">
					    <input type="checkbox" class="form-check-input" id="visa1">
					    <label class="form-check-label" for="visa1">Visa</label>
					</div>
					<div class="form-check mr-4">
					    <input type="checkbox" class="form-check-input" id="card1">
					    <label class="form-check-label" for="card1">Master Card</label>
					</div>
				</div>
				<div class="row">
					<div class="col-6">
						<div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label" style="white-space: nowrap;">Card No.</label>
						    <div class="col-sm-10">
						      <input type="password" class="form-control" id="inputPassword" placeholder="Password">
						    </div>
						  </div>
					</div>
					<div class="col-6">
						<div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">Exp:</label>
						    <div class="col-sm-10">
						      <input type="password" class="form-control" id="inputPassword" placeholder="Password">
						    </div>
						 </div>
					</div>
				</div>
				<strong>PAYMENTIN FIUI I TO RF MADE UPON COMPLETION OF INSTALLATION. IINIFSS OTHFRWISE NOTED.</strong>
				<div class="row">
					<div class="col-6">
						<div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">Signature:</label>
						    <div class="col-sm-10 office-text">
						      <input type="password" class="form-control" id="inputPassword">
						    </div>
						 </div>
					</div>
					<div class="col-6">
						<div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">Signature:</label>
						    <div class="col-sm-10 office-text">
						      <input type="password" class="form-control" id="inputPassword">
						    </div>
						 </div>
					</div>
				</div>
				<strong>BALANCE DUE WILL BE CHARGED TO CARD ON FILE</strong>
  		</div>
		



 
            
        <!-- Main end -->
        <!--=============== scripts  ===============-->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="js/jquery.min.js"></script>      
        <script src="js/bootstrap.min.js"></script>
        <script src="js/scripts.js"></script>
        <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    </body>
    
</html>

templates/order-listing.html
{% extends "base.html" %}
{% load static %}


{% block content %}
 <!-- Form section start  -->
             <section class="form-section all-page-mg">
                <div class="container">
                	<div class="alert-success alert" style="text-align: center; display: none;"></div>
                	<div class="Customer-lsit-table">
						<table class="table">
						  <thead>
						    <tr>
						      <th scope="col">#</th>
						      <th scope="col">Order ID</th>
						      <th scope="col">First Name</th>
						      <th scope="col">E-mail ID</th>
						      <th scope="col">Action</th>
						    </tr>
						  </thead>
						  <tbody>
						  	{% for order in orders %}
						    <tr>
						      <th scope="row">{{forloop.counter}}</th>
						      <td>{{order.order_id}}</td>
						      <td>{{order.customer.user.first_name}}</td>
						      <td>{{order.customer.user.email}}</td>
						      <td><span class="mr-2"><a href="{% url 'edit-order' order.id %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a></span>
						      	<span class=""><i class="fa fa-trash delete-order" data-id = '{{order.id}}' aria-hidden="true"></i></span></td>
						    </tr>
						    {% endfor %}
						    
						  </tbody>
						</table>	
                        <!-- <div class="text-center"><button class="btn-success btn">Submit</button></div> -->
                    </div>
                </div>
             </section>
      {% endblock %}

{% block extrascript %}
<script type="text/javascript">

var msg = localStorage.getItem('success_msg');
if (msg){
	$('.alert-success').append(msg);
	$('.alert-success').show();
}


$('.delete-order').click(function(){
	localStorage.removeItem('success_msg');
	var order_id = $(this).attr('data-id');
	   $.ajax({
			url: '{% url "order-delete" %}',
			type: 'POST',
			data:{
				'csrfmiddlewaretoken':'{{ csrf_token }}',
				'delete_order_id':order_id,
			},
			success: function(response){
				if (response.status == true){
					window.location.reload();
				}
			}

		})
})

</script>

{% endblock %}